version: '3.8'

services:
  retroarch-sync:
    #image: debian:stable
    build: .
    image: retroarch-sync-img
    container_name: retroarch-sync
    restart: "unless-stopped"

    environment:
      - TZ=Europe/Berlin
      - LOCAL_BASE_DIR=/syncfolder
      - ATVHOST=192.168.X.X
      - ATVPORT=80

    volumes:
      - /volume2/homes/al/RetroArch/_sync-atv/retroarch-sync-docker.sh:/retroarch-sync.sh:ro
      - /volume2/homes/al/RetroArch/_sync-atv/dockercontent:/syncfolder
      - /volume2/homes/al/RetroArch/_sync-atv:/hostlog

    working_dir: /data

    entrypoint: ["/bin/sh", "-c", "/retroarch-sync.sh >> /hostlog/retroarch-sync-docker.log 2>&1"]
